algoritmo "86"
//Crie um programa que tenha um procedimento Gerador() que, quando chamado,
//mostre a mensagem "Olá, Mundo!" com algum componente visual (linhas)
//Ex: Ao chamar Gerador() aparece:
var

procedimento Gerador()
inicio
   escreval("+-------=======------+")
   escreval("      Ola, Mundo!     ")
   escreval("+-------=======------+")
fimprocedimento
inicio
      Gerador()
fimalgoritmo