algoritmo "area_retangulo"
var
  L, C, A, T: Inteiro
inicio
      Escreva("Informe a largura do retangulo: ")
      Leia(L)
      Escreva("Informe o comprimento do retangulo: ")
      Leia(C)
      Escreva("Informe a altura do retangulo: ")
      Leia(A)
      T <- L * C * A
      Escreva("A area do retangulo de lado ", L, " comprimento ", C, " e altura ", A, " eh igual a ", T)
fimalgoritmo
